import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import gmailRouter from "./gmail";
import calendarRouter from "./calendar";
import aiRouter from "./ai";
import agentRouter from "./agent";
import historyRouter from "./history";
import billingRouter from "./billing";
import settingsRouter from "./settings";
import googleAuthRouter from "./googleAuth";
import connectorsRouter from "./connectors";
import hubspotAuthRouter from "./hubspotAuth";
import googleExtendRouter from "./googleExtend";
import hubspotRouter from "./hubspot";
import driveRouter from "./drive";
import contactsRouter from "./contacts";
import githubAuthRouter from "./githubAuth";
import linearAuthRouter from "./linearAuth";
import linkedinAuthRouter from "./linkedinAuth";
import linkedinRouter from "./linkedin";
import slackAuthRouter from "./slackAuth";
import slackRouter from "./slack";
import calendlyAuthRouter from "./calendlyAuth";
import calendlyRouter from "./calendly";
import zoomAuthRouter from "./zoomAuth";
import teamsAuthRouter from "./teamsAuth";
import teamsActionsRouter from "./teamsActions";
import fathomAuthRouter from "./fathomAuth";
import fathomRouter from "./fathom";
import scheduledEmailRouter from "./scheduledEmail";
import pushTokenRouter from "./pushToken";
import accountRouter from "./account";
import categoriesRouter from "./categories";
import followUpRemindersRouter from "./followUpReminders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(googleAuthRouter);
router.use(googleExtendRouter);
router.use(hubspotAuthRouter);
router.use(linkedinAuthRouter);
router.use(slackAuthRouter);
router.use(calendlyAuthRouter);
router.use(zoomAuthRouter);
router.use(teamsAuthRouter);
router.use(teamsActionsRouter);
router.use(fathomAuthRouter);
router.use(fathomRouter);
router.use(gmailRouter);
router.use(calendarRouter);
router.use(aiRouter);
router.use(agentRouter);
router.use(historyRouter);
router.use(billingRouter);
router.use(settingsRouter);
router.use(connectorsRouter);
router.use(hubspotRouter);
router.use(linkedinRouter);
router.use(slackRouter);
router.use(calendlyRouter);
router.use(driveRouter);
router.use(contactsRouter);
router.use(githubAuthRouter);
router.use(linearAuthRouter);
router.use(scheduledEmailRouter);
router.use(pushTokenRouter);
router.use(accountRouter);
router.use(categoriesRouter);
router.use(followUpRemindersRouter);

export default router;
